[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.build]
cmds = [
  "cd server && npm install",
  "cd server && npm run init-db"
]

[start]
cmd = "cd server && npm start"

[variables]
NIXPACKS_NPM_INSTALL_COMMAND = "npm install"
