version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: paradise_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: PARADISE251208
      MYSQL_DATABASE: paradise_shop
      MYSQL_USER: paradise_user
      MYSQL_PASSWORD: PARADISE251208
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
